services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tap-hoa-be
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    ports:
      - 8888:3003
